defaultBaseImage: gcr.io/distroless/static-debian12:nonroot@sha256:b7bb25d9f7c31d2bdd1982feb4dafcaf137703c7075dbe2febb41c24212b946f
defaultPlatforms:
  - linux/amd64
  - linux/arm64
defaultEnv:
  - CGO_ENABLED=0
baseImageOverrides:
  github.com/Amoenus/waycloak/cmd/waycloak-node-agent: gcr.io/distroless/static-debian12@sha256:a9fcaedd4c9b59e12dd65d954f0b5044f19b0647a8a3712e77205df9e7b102cd
builds:
  - id: waycloak-cni
    dir: .
    main: ./cmd/waycloak-cni
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -buildid=
  - id: waycloak-node-agent
    dir: .
    main: ./cmd/waycloak-node-agent
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -buildid=
  - id: replacement-controller
    dir: .
    main: ./cmd/replacement-controller
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -buildid=
