// Copyright 2026 The Waycloak Authors.
// SPDX-License-Identifier: MIT

package status

import (
	apiMeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	ConditionAccepted                     = "Accepted"
	ConditionAllocated                    = "Allocated"
	ConditionAllocationPublished          = "AllocationPublished"
	ConditionScheduled                    = "Scheduled"
	ConditionTunnelReady                  = "TunnelReady"
	ConditionOverlayReady                 = "OverlayReady"
	ConditionDNSReady                     = "DNSReady"
	ConditionPortForwardReady             = "PortForwardReady"
	ConditionProviderLeaseReady           = "ProviderLeaseReady"
	ConditionGatewayRulesReady            = "GatewayRulesReady"
	ConditionTargetReady                  = "TargetReady"
	ConditionDelivered                    = "Delivered"
	ConditionReady                        = "Ready"
	ReasonAccepted                        = "Accepted"
	ReasonInvalidOverlay                  = "InvalidOverlay"
	ReasonAllocationPending               = "AllocationPending"
	ReasonAllocationPersisted             = "AllocationPersisted"
	ReasonAllocationConfigMapReady        = "AllocationConfigMapReady"
	ReasonDataPlaneNotImplemented         = "DataPlaneNotImplemented"
	ReasonInvalidEngineImage              = "InvalidEngineImage"
	ReasonInvalidCredentialsReference     = "InvalidCredentialsReference"
	ReasonGatewayResourcesReady           = "GatewayResourcesReady"
	ReasonGatewayPodPending               = "GatewayPodPending"
	ReasonGatewayPodScheduled             = "GatewayPodScheduled"
	ReasonTunnelObservedReady             = "TunnelObservedReady"
	ReasonTunnelNotReady                  = "TunnelNotReady"
	ReasonOverlayObservedReady            = "OverlayObservedReady"
	ReasonOverlayNotReady                 = "OverlayNotReady"
	ReasonOverlayNotImplemented           = "OverlayNotImplemented"
	ReasonDNSObservedReady                = "DNSObservedReady"
	ReasonDNSNotReady                     = "DNSNotReady"
	ReasonPortForwardDisabled             = "PortForwardDisabled"
	ReasonPortForwardObservedReady        = "PortForwardObservedReady"
	ReasonPortForwardNotReady             = "PortForwardNotReady"
	ReasonLeaseAccepted                   = "LeaseAccepted"
	ReasonInvalidTargetSelector           = "InvalidTargetSelector"
	ReasonPortForwardUnsupported          = "PortForwardUnsupported"
	ReasonTargetNotFound                  = "TargetNotFound"
	ReasonTargetAmbiguous                 = "TargetAmbiguous"
	ReasonTargetGatewayMismatch           = "TargetGatewayMismatch"
	ReasonTargetRegistrationPending       = "TargetRegistrationPending"
	ReasonTargetObservedReady             = "TargetObservedReady"
	ReasonProviderLeasePending            = "ProviderLeasePending"
	ReasonProviderLeaseObservedReady      = "ProviderLeaseObservedReady"
	ReasonProviderLeaseObservationFailed  = "ProviderLeaseObservationFailed"
	ReasonProviderLeaseExpired            = "ProviderLeaseExpired"
	ReasonGatewayRulesPending             = "GatewayRulesPending"
	ReasonGatewayRulesObservedReady       = "GatewayRulesObservedReady"
	ReasonDeliveryPending                 = "DeliveryPending"
	ReasonDeliveryObservationFailed       = "DeliveryObservationFailed"
	ReasonDeliveryObservedReady           = "DeliveryObservedReady"
	ReasonLeaseComponentsNotReady         = "LeaseComponentsNotReady"
	ReasonLeaseReady                      = "LeaseReady"
	ReasonGatewayReady                    = "GatewayReady"
	ReasonGatewayComponentsNotReady       = "GatewayComponentsNotReady"
	ReasonGatewayNotFound                 = "GatewayNotFound"
	ReasonUnauthorizedGateway             = "UnauthorizedGateway"
	ReasonAdmissionGenerationConflict     = "AdmissionGenerationConflict"
	ReasonAdmissionVersionConflict        = "AdmissionVersionConflict"
	ReasonApplicationCredentialsForbidden = "ApplicationCredentialsForbidden"
)

func Set(conditions *[]metav1.Condition, generation int64, typ string, value metav1.ConditionStatus, reason, message string) {
	apiMeta.SetStatusCondition(conditions, metav1.Condition{Type: typ, Status: value, ObservedGeneration: generation, Reason: reason, Message: message})
}
