// Copyright 2026 The Waycloak Authors.
// SPDX-License-Identifier: MIT

// Command apireference renders deterministic replacement API documentation
// from the generated CRDs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

var kindOrder = []string{
	"VPNGatewayClass",
	"VPNGateway",
	"VPNEgressRoute",
	"VPNWorkloadBinding",
	"PortForwardLease",
	"WorkloadAdapter",
}

type customResourceDefinition struct {
	Metadata struct {
		Name string `json:"name"`
	} `json:"metadata"`
	Spec struct {
		Group string `json:"group"`
		Scope string `json:"scope"`
		Names struct {
			Kind     string `json:"kind"`
			Plural   string `json:"plural"`
			Singular string `json:"singular"`
		} `json:"names"`
		Versions []struct {
			Name    string `json:"name"`
			Served  bool   `json:"served"`
			Storage bool   `json:"storage"`
			Schema  struct {
				OpenAPIV3Schema jsonSchema `json:"openAPIV3Schema"`
			} `json:"schema"`
			Subresources struct {
				Status map[string]any `json:"status"`
			} `json:"subresources"`
		} `json:"versions"`
	} `json:"spec"`
}

type jsonSchema struct {
	Type        string                `json:"type"`
	Format      string                `json:"format"`
	Description string                `json:"description"`
	Required    []string              `json:"required"`
	Properties  map[string]jsonSchema `json:"properties"`
	Items       *jsonSchema           `json:"items"`
	IntOrString bool                  `json:"x-kubernetes-int-or-string"`
}

func main() {
	crdDir := flag.String("crd-dir", "config/crd/bases", "generated CRD directory")
	output := flag.String("output", "docs/api/v1beta1.md", "generated Markdown output")
	flag.Parse()
	data, err := render(*crdDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, data, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write API reference: %v\n", err)
		os.Exit(1)
	}
}

func render(crdDir string) ([]byte, error) {
	entries, err := os.ReadDir(crdDir)
	if err != nil {
		return nil, fmt.Errorf("read CRD directory: %w", err)
	}
	byKind := map[string]customResourceDefinition{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}
		data, readErr := os.ReadFile(filepath.Join(crdDir, entry.Name()))
		if readErr != nil {
			return nil, fmt.Errorf("read %s: %w", entry.Name(), readErr)
		}
		var crd customResourceDefinition
		if unmarshalErr := yaml.Unmarshal(data, &crd); unmarshalErr != nil {
			return nil, fmt.Errorf("decode %s: %w", entry.Name(), unmarshalErr)
		}
		if crd.Spec.Group != "networking.waycloak.io" {
			continue
		}
		byKind[crd.Spec.Names.Kind] = crd
	}
	if len(byKind) != len(kindOrder) {
		return nil, fmt.Errorf("found %d replacement CRDs, want %d", len(byKind), len(kindOrder))
	}

	var output bytes.Buffer
	output.WriteString("<!-- Code generated by hack/apireference. DO NOT EDIT. -->\n\n")
	output.WriteString("# Waycloak v1beta1 API reference\n\n")
	output.WriteString("All resources use `networking.waycloak.io/v1beta1`. Unknown fields are rejected by the structural CRD schemas. This reference documents the generated API surface; controller behavior and live readiness semantics are specified in the stable product documents and ADRs.\n\n")
	output.WriteString("Every reconciled user-facing resource exposes positive-polarity `Accepted`, `ResolvedRefs`, `Programmed`, and `Ready` conditions. `Ready` represents observed live data-plane health.\n")

	for _, kind := range kindOrder {
		crd, ok := byKind[kind]
		if !ok {
			return nil, fmt.Errorf("replacement CRD %s is missing", kind)
		}
		if err := renderCRD(&output, crd); err != nil {
			return nil, err
		}
	}
	return output.Bytes(), nil
}

func renderCRD(output *bytes.Buffer, crd customResourceDefinition) error {
	var version *struct {
		Name    string `json:"name"`
		Served  bool   `json:"served"`
		Storage bool   `json:"storage"`
		Schema  struct {
			OpenAPIV3Schema jsonSchema `json:"openAPIV3Schema"`
		} `json:"schema"`
		Subresources struct {
			Status map[string]any `json:"status"`
		} `json:"subresources"`
	}
	for index := range crd.Spec.Versions {
		if crd.Spec.Versions[index].Name == "v1beta1" {
			version = &crd.Spec.Versions[index]
			break
		}
	}
	if version == nil || !version.Served || !version.Storage {
		return fmt.Errorf("%s must serve and store v1beta1", crd.Spec.Names.Kind)
	}
	root := version.Schema.OpenAPIV3Schema
	spec, ok := root.Properties["spec"]
	if !ok {
		return fmt.Errorf("%s has no spec schema", crd.Spec.Names.Kind)
	}
	status, ok := root.Properties["status"]
	if !ok {
		return fmt.Errorf("%s has no status schema", crd.Spec.Names.Kind)
	}

	fmt.Fprintf(output, "\n## %s\n\n", crd.Spec.Names.Kind)
	fmt.Fprintf(output, "- Scope: `%s`\n", crd.Spec.Scope)
	fmt.Fprintf(output, "- Resource: `%s`\n", crd.Metadata.Name)
	fmt.Fprintf(output, "- Status subresource: `%t`\n", version.Subresources.Status != nil)
	renderFields(output, "Spec", spec)
	renderFields(output, "Status", status)
	return nil
}

func renderFields(output *bytes.Buffer, heading string, schema jsonSchema) {
	fmt.Fprintf(output, "\n### %s fields\n\n", heading)
	output.WriteString("| Field | Required | Type | Description |\n")
	output.WriteString("| --- | --- | --- | --- |\n")
	required := make(map[string]bool, len(schema.Required))
	for _, field := range schema.Required {
		required[field] = true
	}
	names := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		property := schema.Properties[name]
		fmt.Fprintf(output, "| `%s` | %t | `%s` | %s |\n", name, required[name], schemaType(property), summary(property.Description))
	}
}

func schemaType(schema jsonSchema) string {
	if schema.IntOrString {
		return "integer|string"
	}
	result := schema.Type
	if result == "array" && schema.Items != nil {
		result = "array<" + schemaType(*schema.Items) + ">"
	}
	if schema.Format != "" {
		result += " (" + schema.Format + ")"
	}
	return result
}

func summary(description string) string {
	description = strings.TrimSpace(description)
	if index := strings.Index(description, "\n"); index >= 0 {
		description = description[:index]
	}
	description = strings.ReplaceAll(description, "|", "\\|")
	if description == "" {
		return "—"
	}
	return description
}
