apiVersion: networking.waycloak.io/v1alpha1
kind: VPNGateway
metadata:
  name: example
  namespace: waycloak-egress
spec:
  engine:
    type: Gluetun
    image: docker.io/qmcgaw/gluetun:v3.41.0@sha256:6b54856716d0de56e5bb00a77029b0adea57284cf5a466f23aad5979257d3045
  provider:
    name: protonvpn
    protocol: OpenVPN
    region: Netherlands
    credentialsSecretRef:
      name: vpn-credentials
  overlay:
    cidr: 172.30.99.0/24
    vni: 7999
    mtu: 1320
  workloadAccess:
    namespaceSelector:
      matchLabels:
        networking.waycloak.io/access: allowed
