apiVersion: v2
name: waycloak
description: Declarative, fail-closed private egress for Kubernetes
type: application
version: 0.3.0-rc.8
appVersion: 0.3.0-rc.8
kubeVersion: ">=1.30.0-0"
home: https://github.com/Amoenus/waycloak
sources:
  - https://github.com/Amoenus/waycloak
annotations:
  licenses: MIT
