---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: waycloak-distribution
rules:
- apiGroups:
  - networking.waycloak.io
  resources:
  - vpngatewayclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
