//go:build !ignore_autogenerated

// Copyright 2026 The Waycloak Authors.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationConfig) DeepCopyInto(out *InstallationConfig) {
	*out = *in
	in.ControllerResources.DeepCopyInto(&out.ControllerResources)
	in.NodeAgentResources.DeepCopyInto(&out.NodeAgentResources)
	in.InstallerResources.DeepCopyInto(&out.InstallerResources)
	if in.ControllerNodeSelector != nil {
		in, out := &in.ControllerNodeSelector, &out.ControllerNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ControllerTolerations != nil {
		in, out := &in.ControllerTolerations, &out.ControllerTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PortForwarding != nil {
		in, out := &in.PortForwarding, &out.PortForwarding
		*out = new(PortForwarding)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationConfig.
func (in *InstallationConfig) DeepCopy() *InstallationConfig {
	if in == nil {
		return nil
	}
	out := new(InstallationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortForwarding) DeepCopyInto(out *PortForwarding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortForwarding.
func (in *PortForwarding) DeepCopy() *PortForwarding {
	if in == nil {
		return nil
	}
	out := new(PortForwarding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaycloakInstallation) DeepCopyInto(out *WaycloakInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaycloakInstallation.
func (in *WaycloakInstallation) DeepCopy() *WaycloakInstallation {
	if in == nil {
		return nil
	}
	out := new(WaycloakInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WaycloakInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaycloakInstallationList) DeepCopyInto(out *WaycloakInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WaycloakInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaycloakInstallationList.
func (in *WaycloakInstallationList) DeepCopy() *WaycloakInstallationList {
	if in == nil {
		return nil
	}
	out := new(WaycloakInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WaycloakInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaycloakInstallationSpec) DeepCopyInto(out *WaycloakInstallationSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaycloakInstallationSpec.
func (in *WaycloakInstallationSpec) DeepCopy() *WaycloakInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(WaycloakInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaycloakInstallationStatus) DeepCopyInto(out *WaycloakInstallationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaycloakInstallationStatus.
func (in *WaycloakInstallationStatus) DeepCopy() *WaycloakInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(WaycloakInstallationStatus)
	in.DeepCopyInto(out)
	return out
}
